#define MAJOR 2
#define MINOR 6
#define PATCH 0
#define BUILD 447


// #define VERSION MACROS
#define VERSION MAJOR.MINOR
#define VERSION_AR MAJOR,MINOR,PATCH
#define VERSION_STR MAJOR##.##MINOR##.##PATCH
