[base]
mission = "test.VR"
workshop = [
    "450814997",  # CBA_A3's Workshop ID
    "3499977893", # Advanced Developer Tools
]
dlc = [
]

optionals = [
]

parameters = [
    "-window",
    "-noPause",
    "-noPauseAudio",
]

[default]
extends = "base"
workshop = [
    "463939057",  # ACE3
    "1779063631", # ZEN
]

# executable = "arma3_x64"        # Default: "arma3_x64"
# file_patching = true # Default: true
# binarize = false # Default: false
# rapify = true # Default: true


[asp]
extends = "default"
workshop = [
    "1645973522", # Intercept Minimal Dev
    "1652506957", # Arma Script Profiler
]

[light]
extends = "default"
mission = "test.altis"
workshop = [
    "1613905318", # Emitter 3Ditor
]
